# NumPy Tutorial: Basics for Machine Learning


**NumPy** (short for Numerical Python) is a powerful open-source Python library used for numerical computing. It provides support for working with arrays, matrices, and a variety of mathematical functions to perform operations on these data structures efficiently. NumPy is a fundamental package for scientific computing in Python and serves as the base for many other libraries like Pandas, SciPy, and scikit-learn.

### Key Features of NumPy:

1. N-dimensional Array (ndarray):** 

- Core data structure of NumPy.
- Provides efficient storage and operations for homogeneous data (all elements of the same type).

2. Mathematical Functions:

- Supports a wide range of mathematical operations, such as addition, subtraction, multiplication, division, trigonometry, and more.

3. Broadcasting:

- Enables operations on arrays of different shapes without requiring explicit loops.

4. Linear Algebra:

- Provides support for linear algebra operations such as matrix multiplication, eigenvalues, determinants, and solving linear equations.

5. Random Number Generation:

- Functions to generate random numbers, random samples, and perform random sampling.

6. Efficient Performance:

- Optimized for performance with implementations in C, allowing fast execution for large-scale numerical computations.

### Why Use NumPy?

- **Performance:** It is much faster than standard Python lists for numerical operations because of its optimized C implementation.

- **Memory Efficiency:** Consumes less memory compared to Python lists for storing large datasets.

- **Ease of Use:** Provides concise syntax for complex numerical operations.

- **Compatibility:** Integrates seamlessly with other scientific libraries like Pandas, Matplotlib, and SciPy.

In [1]:
# Import the NumPy library
import numpy as np


### Creating Arrays

In [2]:
# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)


1D Array: [1 2 3 4 5]


In [3]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)



2D Array:
[[1 2 3]
 [4 5 6]]


In [4]:
# Create an array with zeros
zeros = np.zeros((2, 3))
print("\nArray of Zeros:")
print(zeros)


Array of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:

# Create an array with ones
ones = np.ones((3, 2))
print("\nArray of Ones:")
print(ones)


Array of Ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:

# Create an array with a range of numbers
range_array = np.arange(0, 10, 2)
print("\nArray with a Range of Numbers:", range_array)



Array with a Range of Numbers: [0 2 4 6 8]


In [7]:
# Create an array with evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)
print("\nArray with Evenly Spaced Numbers:", linspace_array)



Array with Evenly Spaced Numbers: [0.   0.25 0.5  0.75 1.  ]


### 2. Array Operations


In [8]:
# Element-wise addition
array_sum = array_1d + 5
print("\nElement-wise Addition:", array_sum)



Element-wise Addition: [ 6  7  8  9 10]


In [9]:
# Element-wise multiplication
array_mult = array_1d * 2
print("\nElement-wise Multiplication:", array_mult)



Element-wise Multiplication: [ 2  4  6  8 10]


In [10]:


# Element-wise square
array_square = array_1d ** 2
print("\nElement-wise Square:", array_square)


Element-wise Square: [ 1  4  9 16 25]


In [11]:

# Element-wise division
array_div = array_1d / 2
print("\nElement-wise Division:", array_div)


Element-wise Division: [0.5 1.  1.5 2.  2.5]


In [12]:
# Accessing an element
print("\nFirst Element of 1D Array:", array_1d[0])



First Element of 1D Array: 1


In [13]:
# Slicing
print("\nSlice 1D Array [1:4]:", array_1d[1:4])



Slice 1D Array [1:4]: [2 3 4]


In [14]:
# Accessing elements in 2D arrays
print("\nElement at (0, 1) in 2D Array:", array_2d[0, 1])



Element at (0, 1) in 2D Array: 2


In [15]:

# Boolean indexing
bool_idx = array_1d > 3
print("\nBoolean Indexing (Array > 3):", bool_idx)
print("Filtered Elements:", array_1d[bool_idx])



Boolean Indexing (Array > 3): [False False False  True  True]
Filtered Elements: [4 5]


### 3. Array Properties

In [16]:


print("\nShape of 2D Array:", array_2d.shape)
print("Number of Dimensions:", array_2d.ndim)
print("Data Type:", array_2d.dtype)
print("Size of Array:", array_2d.size)



Shape of 2D Array: (2, 3)
Number of Dimensions: 2
Data Type: int64
Size of Array: 6


### 4. Reshaping Arrays

In [17]:


reshaped_array = array_1d.reshape((1, 5))
print("\nReshaped Array:")
print(reshaped_array)



Reshaped Array:
[[1 2 3 4 5]]


### 5. Flattening an array


In [18]:
flattened = array_2d.flatten()
print("\nFlattened Array:", flattened)



Flattened Array: [1 2 3 4 5 6]



### 6. Mathematical Functions


In [20]:
# Calculate the mean
mean_value = np.mean(array_1d)
print("\nMean:", mean_value)



Mean: 3.0


In [21]:

# Calculate the standard deviation
std_value = np.std(array_1d)
print("Standard Deviation:", std_value)




Standard Deviation: 1.4142135623730951


In [22]:
# Find the maximum and minimum
max_value = np.max(array_1d)
min_value = np.min(array_1d)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)



Maximum Value: 5
Minimum Value: 1


In [23]:
# Sum of all elements
sum_value = np.sum(array_1d)
print("Sum of Elements:", sum_value)

Sum of Elements: 15


### 7. Random Number Generation

In [26]:

random_array = np.random.rand(3, 3)
print("\nRandom Array:")
print(random_array)


Random Array:
[[0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


In [27]:

# Generate random integers
random_integers = np.random.randint(0, 10, (3, 3))
print("\nRandom Integers Array:")
print(random_integers)



Random Integers Array:
[[5 1 4]
 [0 9 5]
 [8 0 9]]


In [28]:



# Set a seed for reproducibility
np.random.seed(42)
seeded_random = np.random.rand(3)
print("\nSeeded Random Array:", seeded_random)


Seeded Random Array: [0.37454012 0.95071431 0.73199394]


### 8. Matrix Operations

In [29]:
# Matrix multiplication using np.dot
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(matrix_a, matrix_b)
print("\nMatrix Product (using np.dot):")
print(matrix_product)


Matrix Product (using np.dot):
[[19 22]
 [43 50]]


In [30]:
# Matrix multiplication using @ operator
matrix_product_at = matrix_a @ matrix_b
print("\nMatrix Product (using @ operator):")
print(matrix_product_at)



Matrix Product (using @ operator):
[[19 22]
 [43 50]]


In [31]:
# Transpose of a matrix
matrix_transpose = matrix_a.T
print("\nTranspose of Matrix A:")
print(matrix_transpose)



Transpose of Matrix A:
[[1 3]
 [2 4]]


In [32]:
# Inverse of a matrix
matrix_square = np.array([[1, 2], [3, 4]])
matrix_inverse = np.linalg.inv(matrix_square)
print("\nInverse of Matrix:")
print(matrix_inverse)



Inverse of Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [33]:
# Determinant of a matrix
matrix_determinant = np.linalg.det(matrix_square)
print("\nDeterminant of Matrix:", matrix_determinant)


Determinant of Matrix: -2.0000000000000004


### 9. Logical Operations

In [34]:

logical_array = array_1d > 3
print("\nLogical Operation (Array > 3):")
print(logical_array)



Logical Operation (Array > 3):
[False False False  True  True]


In [35]:

# Check if all elements satisfy a condition
all_condition = np.all(array_1d > 0)
print("\nAll Elements > 0:", all_condition)


All Elements > 0: True


In [36]:
# Check if any element satisfies a condition
any_condition = np.any(array_1d > 4)
print("Any Element > 4:", any_condition)

Any Element > 4: True



# 10. Broadcasting


In [37]:
# Add a scalar to a 2D array
broadcast_add = array_2d + 5
print("\nBroadcast Addition:")
print(broadcast_add)


Broadcast Addition:
[[ 6  7  8]
 [ 9 10 11]]


In [38]:
# Multiply a 1D array with a 2D array
broadcast_mult = array_2d * array_1d[:3]
print("\nBroadcast Multiplication:")
print(broadcast_mult)



Broadcast Multiplication:
[[ 1  4  9]
 [ 4 10 18]]


### 11. Saving and Loading Arrays

In [39]:

# Save an array to a file
np.save("array_file.npy", array_1d)
print("\nArray saved to 'array_file.npy'")


Array saved to 'array_file.npy'


In [40]:
# Load an array from a file
loaded_array = np.load("array_file.npy")
print("Loaded Array:", loaded_array)

Loaded Array: [1 2 3 4 5]


In [41]:
# Save to a text file
np.savetxt("array_file.txt", array_2d, delimiter=",")
print("\nArray saved to 'array_file.txt'")


Array saved to 'array_file.txt'


In [42]:
# Load from a text file
loaded_text_array = np.loadtxt("array_file.txt", delimiter=",")
print("Loaded Text Array:")
print(loaded_text_array)

Loaded Text Array:
[[1. 2. 3.]
 [4. 5. 6.]]


### 12.  Indexing


In [43]:
# Indexing with arrays
indices = [0, 2, 4]
print("\nIndexing Result:", array_1d[indices])


Indexing Result: [1 3 5]


In [44]:
# Boolean indexing
bool_idx = array_1d > 3
print("\nBoolean Indexing Result:", array_1d[bool_idx])


Boolean Indexing Result: [4 5]


In [45]:
# Fancy indexing
fancy_idx = np.array([0, 2, 4])
print("\nFancy Indexing Result:", array_1d[fancy_idx])



Fancy Indexing Result: [1 3 5]
